#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2ef9f9ed-d00e-4d11-92a9-ee22945d27a1 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String ledStatus;
  String msg;
  int ledPin;
  int soilsensor;
  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define sensorPin 36
#define ledPin 2
extern String ledStatus;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  pinMode(sensorPin,INPUT);
  pinMode(ledPin,OUTPUT);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  int sensorValue=analogRead(sensorPin);
  Serial.println(sensorValue);
  soilsensor=sensorValue;

  if(sensorValue<500){
    Serial.println("Condition: Dry");
    led = 0;
    msg="Dry";
    digitalWrite(ledPin, HIGH);
    ledStatus = "Red";
  }
  else{
    Serial.println("Condition: Wet");
    digitalWrite(ledPin, LOW);
    led = 1;
    msg="Wet";
    ledStatus = "Green";
  }
  delay(2000);
}


void onSensorPinChange(){
  
}
/*
  Since LedPin is READ_WRITE variable, onLedPinChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedPinChange()  {
  // Add your code here to act upon LedPin change
}



/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  // Add your code here to act upon Led change
}

/*
  Since Msg is READ_WRITE variable, onMsgChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMsgChange()  {
  // Add your code here to act upon Msg change
}